---
- name: Install Docker
  hosts: localhost
  gather_facts: true
  become: true

  roles:
    - role: geerlingguy.docker
      vars:
        docker_users:
          - dkravets
          - ubuntu
        docker_install_compose: true

