# load zgenom
source "${HOME}/.zgenom/zgenom.zsh"

if ! zgenom saved; then

  # specify plugins here
  zgenom ohmyzsh

  zgenom ohmyzsh plugins/git
  zgenom load zsh-users/zsh-syntax-highlighting

  for file in ~/.zsh/includes/*; do
      zgenom load ${file}
  done

  # completions
  zgenom load zsh-users/zsh-completions

  # theme
  zgenom ohmyzsh themes/jonathan

  # save all to init script
  zgenom save

  # Compile your zsh files
  zgenom compile "$HOME/.zshrc"
fi

export PATH=~/.local/bin:$PATH
